window.YUANSHAN_PLACES = [
  {id:'chen-fish',name:'陳茂庚員山魚丸米粉',cat:'小吃',emoji:'🍜',address:'宜蘭縣員山鄉員山路一段269號',desc:'員山經典魚丸米粉老店，適合早餐到午餐時段。',hours:'06:30–15:00（週三常休）',tags:['魚丸米粉','老店']},
  {id:'dabao',name:'大寶魚丸米粉',cat:'小吃',emoji:'🍜',address:'宜蘭縣員山鄉員山路一段272號',desc:'員山街上方便好找的魚丸米粉，在地味路線。',hours:'約 10:30–22:00',tags:['魚丸米粉','在地']},
  {id:'lu-fish',name:'呂家傳統魚丸米粉',cat:'小吃',emoji:'🥣',address:'宜蘭縣員山鄉員山路一段173號',desc:'手工魚丸、清甜湯頭，是員山魚丸米粉代表之一。',hours:'約 11:00–19:00',tags:['魚丸米粉','手工']},
  {id:'wu-fish',name:'吳家魚丸米粉店',cat:'小吃',emoji:'🥣',address:'宜蘭縣員山鄉員山路一段338號',desc:'員山市區另一個魚丸米粉選擇，從早到晚較好安排。',hours:'約 08:00–19:00',tags:['魚丸米粉','小吃']},
  {id:'meigongzi',name:'美公子湯包',cat:'小吃',emoji:'🥟',address:'宜蘭縣員山鄉永同路一段170號',desc:'現蒸湯包系小店，適合排進午餐或下午點心。',hours:'約 10:00–18:00',tags:['湯包','點心']},
  {id:'star-pot',name:'星之鍋・蒜了啦',cat:'小吃',emoji:'🍲',address:'宜蘭縣員山鄉員山路一段375號1樓',desc:'主打小卷、魚丸米粉鍋等暖胃鍋物。',hours:'約 11:00–18:30',tags:['鍋物','海鮮']},
  {id:'grandma-tofu',name:'阿嬤臭豆腐',cat:'小吃',emoji:'🧈',address:'宜蘭縣員山鄉同新路286號',desc:'外酥內嫩臭豆腐，適合下午到晚間順吃。',hours:'五六日約 11:00–20:00',tags:['臭豆腐','下午茶']},
  {id:'corn',name:'黑連本店－烤玉米',cat:'小吃',emoji:'🌽',address:'宜蘭縣員山鄉同新路329號',desc:'炭烤玉米老味道，下午到宵夜時段都能排。',hours:'平日約 13:30–22:00',tags:['烤玉米','宵夜']},
  {id:'goose',name:'宜蘭望龍埤鵝肉攤',cat:'小吃',emoji:'🪿',address:'宜蘭縣員山鄉坡城路23-12號',desc:'望龍埤旁人氣鵝肉、米粉與熱炒，玩湖區時最順。',hours:'約 10:30–18:30',tags:['鵝肉','望龍埤']},
  {id:'song3',name:'松叁雞',cat:'正餐',emoji:'🍗',address:'宜蘭縣員山鄉隘界一路23巷111號',desc:'窯烤／甕缸雞與合菜，適合家庭聚餐或多人出遊。',hours:'午晚餐；時段依店家公告',tags:['烤雞','合菜']},
  {id:'redwarehouse',name:'紅倉庫桶仔雞',cat:'正餐',emoji:'🍗',address:'宜蘭縣員山鄉長堤路112號',desc:'桶仔雞與多人合菜，開車旅行很適合中途停。',hours:'午、晚餐時段',tags:['桶仔雞','合菜']},
  {id:'wada',name:'和田食堂',cat:'正餐',emoji:'🍣',address:'宜蘭縣員山鄉惠深一路55號',desc:'日式料理與生鮮食材取向，接客數有限，建議先訂位。',hours:'午餐為主；週末部分晚餐',tags:['日本料理','訂位']},
  {id:'hachiko',name:'八甲休閒魚場',cat:'正餐',emoji:'🐟',address:'宜蘭縣員山鄉八甲路1-10號',desc:'香魚與中式合菜，也是員山湧泉養殖特色的一站。',hours:'午餐；假日部分晚餐',tags:['香魚','合菜']},
  {id:'ishikawa',name:'石川手作料理',cat:'正餐',emoji:'🍱',address:'宜蘭縣員山鄉隘界六路68號',desc:'台式手作料理，午晚餐皆可安排。',hours:'約 11:30–14:00 / 17:30–20:30',tags:['台菜','手作料理']},
  {id:'zaodaotian',name:'棗稻田休閒農場',cat:'正餐',emoji:'🌾',address:'宜蘭縣員山鄉員山路二段172巷17號',desc:'田園餐食與休閒農場氛圍，可吃飯也可慢遊。',hours:'約 09:30–17:00',tags:['農場餐廳','田園']},
  {id:'private',name:'嚐藏私廚',cat:'正餐',emoji:'🍽️',address:'宜蘭縣員山鄉惠深二路一段52-1號',desc:'小型私廚餐飲空間，適合想吃得精緻一點的行程。',hours:'建議先電話確認',tags:['私廚','預約']},
  {id:'neihotel',name:'內城大飯店／太祖魷魚羹',cat:'小吃',emoji:'🦑',address:'宜蘭縣員山鄉內城路457號',desc:'名字很氣派、其實是在地小吃店；玩內城時可順吃。',hours:'約 08:00–14:00 / 16:00–18:30',tags:['魷魚羹','內城']},
  {id:'crab-bbq',name:'毛蟹冒泡碳烤屋',cat:'正餐',emoji:'🔥',address:'宜蘭縣員山鄉大湖六路20號',desc:'靠近螃蟹冒泡湧泉的碳烤與中式料理選擇。',hours:'約 11:30–19:30',tags:['碳烤','大湖']},
  {id:'gather',name:'Gather 食聚咖啡',cat:'咖啡',emoji:'🍰',address:'宜蘭縣員山鄉尚深路60巷29號',desc:'水果千層、肉桂捲與甜點人氣店，獨棟空間好停車。',hours:'約 10:00–17:00；常見一二休',tags:['千層蛋糕','甜點']},
  {id:'beihou',name:'北后寺・聽水',cat:'咖啡',emoji:'☕',address:'宜蘭縣員山鄉八甲路4號',desc:'溪水聲與安靜空間是亮點，適合安排一段慢咖啡。',hours:'約 09:30–16:30；以 IG 公告為主',tags:['手沖咖啡','溪畔']},
  {id:'light-home',name:'光宅',cat:'咖啡',emoji:'☕',address:'宜蘭縣員山鄉溪洲路140巷32號',desc:'田間人氣咖啡甜點空間，營業日變動較大。',hours:'請看 IG／FB 最新公告',tags:['咖啡','甜點']},
  {id:'flower-room',name:'花室咖啡',cat:'咖啡',emoji:'🥞',address:'宜蘭縣員山鄉三鬮路213號',desc:'景觀感強的咖啡店，適合厚鬆餅、輕食與拍照。',hours:'營業日較少，出發前務必確認',tags:['景觀咖啡','鬆餅']},
  {id:'yard',name:'小院子咖啡｜畫廊',cat:'咖啡',emoji:'🖼️',address:'宜蘭縣員山鄉德湖路二段21號',desc:'老物件、小院與畫廊感空間，適合午後慢坐。',hours:'多為週三至週日午後',tags:['畫廊','咖啡']},
  {id:'hk-brunch',name:'太平山下史忽仔',cat:'咖啡',emoji:'🥟',address:'宜蘭縣員山鄉七賢路261號1樓',desc:'港式早午餐、點心與私廚料理，帶點香港味。',hours:'部分日 11:00–16:30；私廚採預約',tags:['港式','早午餐']},
  {id:'dough',name:"What's Up Dough? 花莎豆米貝果",cat:'咖啡',emoji:'🥯',address:'宜蘭縣員山鄉八甲路15-16號',desc:'貝果、咖啡與早午餐，和勝洋、花泉在同一帶。',hours:'約 10:00–17:00；假日較長',tags:['貝果','早午餐']},
  {id:'tea',name:'幸福多一點鮮泡茶飲',cat:'咖啡',emoji:'🧋',address:'宜蘭縣員山鄉同新路304號',desc:'在地手搖飲與咖啡，跑景點途中補一杯很方便。',hours:'約 11:00–21:00',tags:['手搖飲','咖啡']},
  {id:'happy-more',name:'樂多廚房 Happy More Brunch',cat:'咖啡',emoji:'🍳',address:'宜蘭縣員山鄉溫泉路95-3號',desc:'早午餐、咖啡與下午茶，一般行程好插入。',hours:'平日約 10:00–16:00；假日較長',tags:['早午餐','咖啡']},
  {id:'good-karma',name:'耕善緣',cat:'咖啡',emoji:'🥛',address:'宜蘭縣員山鄉尚深路84號',desc:'深溝一帶的鮮乳甜點與餐食小店，數量有限時常提早完售。',hours:'下午到晚間；依店家公告',tags:['鮮乳','甜點']},

  {id:'wanglongpi',name:'望龍埤',cat:'自然',emoji:'🌿',address:'宜蘭縣員山鄉枕山村坡城路',desc:'員山代表湖景，環湖步道、紅橋、落羽松與山景一次收。',hours:'約 08:00–18:00',tags:['湖泊','步道','免費']},
  {id:'shuanglianpi',name:'雙連埤野生動物保護區',cat:'自然',emoji:'🦆',address:'宜蘭縣員山鄉湖西村雙埤路',desc:'低海拔濕地、生態與水生植物豐富，適合喜歡自然觀察的人。',hours:'戶外區域依現場規範',tags:['濕地','生態']},
  {id:'fushan',name:'福山植物園',cat:'自然',emoji:'🌲',address:'宜蘭縣員山鄉湖西村雙埤路福山1號',desc:'森林研究與自然教育景點，入園通常需要事先申請。',hours:'09:00–15:00；週二常休',tags:['植物園','需申請']},
  {id:'crab-spring',name:'螃蟹冒泡（地底湧泉）',cat:'自然',emoji:'💧',address:'宜蘭縣員山鄉大湖路18-1號',desc:'清澈地底湧泉與親水感是特色，夏天人氣高。',hours:'戶外空間多為全天',tags:['湧泉','親水']},
  {id:'sun-lake',name:'太陽埤',cat:'自然',emoji:'🌤️',address:'宜蘭縣員山鄉內城村太陽埤',desc:'內城田園與埤塘景觀，適合與鐵牛力阿卡、社區體驗串遊。',hours:'戶外景觀',tags:['埤塘','內城']},
  {id:'lipi',name:'蜊埤湖',cat:'自然',emoji:'🪷',address:'宜蘭縣員山鄉蜊埤路',desc:'環湖綠意與落羽松景觀，適合散步、拍照。',hours:'約白天時段',tags:['湖泊','落羽松']},
  {id:'yuanshan-park',name:'員山公園',cat:'自然',emoji:'🌳',address:'宜蘭縣員山鄉復興路',desc:'在地休憩公園，有步道、活動空間與兒童遊憩區。',hours:'24 小時',tags:['公園','免費']},
  {id:'dajiaoxi',name:'大礁溪農場',cat:'農場',emoji:'🍦',address:'宜蘭縣員山鄉坡城路18-6號',desc:'員山湧泉遊路線中的農遊站，可留意在地農產創意冰品與體驗。',hours:'請先確認預約與開放狀況',tags:['農遊','冰品']},
  {id:'pineapple',name:'二湖鳳梨館',cat:'農場',emoji:'🍍',address:'宜蘭縣員山鄉二湖路108號',desc:'員山無尾鳳梨主題農產據點，適合順路買在地農產。',hours:'約 08:00–18:00',tags:['鳳梨','農產']},
  {id:'shengyang',name:'勝洋休閒農場',cat:'農場',emoji:'🪴',address:'宜蘭縣員山鄉八甲路15-6號',desc:'水草、生態瓶、湧泉與親子體驗，是員山很有代表性的休閒農場。',hours:'約 09:30–17:00；週三四常休',tags:['水草','DIY','親子']},
  {id:'flower-spring',name:'花泉休閒農場',cat:'農場',emoji:'🌼',address:'宜蘭縣員山鄉八甲路15-1號',desc:'天然湧泉、有機野薑花、抓魚摸蜆與食農 DIY，親子很適合。',hours:'約 10:00–17:00',tags:['湧泉','野薑花','親子']},
  {id:'sheep',name:'可達休閒羊場',cat:'農場',emoji:'🐐',address:'宜蘭縣員山鄉惠深二路二段125號',desc:'可餵羊、看小動物、做 DIY，也能品嚐羊奶相關食品。',hours:'約 09:00–17:00',tags:['動物','親子','免費入園']},
  {id:'orchid',name:'金雙甡花卉農場',cat:'農場',emoji:'🌸',address:'宜蘭縣員山鄉枕山路一段68號',desc:'蘭花與花卉農場，適合喜歡園藝與拍花的人。',hours:'約 09:30–18:00',tags:['花卉','蘭花']},
  {id:'bee',name:'興蜂作浪觀光農場',cat:'農場',emoji:'🐝',address:'宜蘭縣員山鄉山前路200巷口',desc:'蜂業與農場體驗，開放時段較集中，安排前先確認。',hours:'多為週末分時段開放',tags:['蜜蜂','食農']},
  {id:'hengshan',name:'橫山頭休閒農業區',cat:'農場',emoji:'🚜',address:'宜蘭縣員山鄉尚德村',desc:'涵蓋內城、尚德、蓁巷等地，主打水資源、田園、農遊與地方體驗。',hours:'各場域依業者公告',tags:['農業區','田園']},

  {id:'herbelle',name:'香草菲菲芳香植物博物館',cat:'親子',emoji:'🌿',address:'宜蘭縣員山鄉內城路650號',desc:'香草植物、溫室空間、餐飲與五感體驗，晴雨天都好排。',hours:'約 09:00–17:30',tags:['香草','室內','親子']},
  {id:'heads-up',name:'頭等倉 Heads Up',cat:'親子',emoji:'🧗',address:'宜蘭縣員山鄉賢德路二段188號',desc:'室內運動挑戰、體能互動與親子放電，雨天備案很實用。',hours:'約 09:00–17:00；週三常休',tags:['室內','親子','雨天']},
  {id:'neicheng',name:'內城社區・鐵牛力阿卡',cat:'文化',emoji:'🚜',address:'宜蘭縣員山鄉榮光路321號',desc:'用鐵牛力阿卡走進農村、水圳、太陽埤與在地生活文化。',hours:'體驗建議事先洽詢社區',tags:['社區','鐵牛車','農村']},
  {id:'air-shelter',name:'員山機堡（神風特攻機堡）',cat:'文化',emoji:'🛩️',address:'宜蘭縣員山鄉金山東路398號',desc:'二戰時期軍事歷史遺跡，適合文化與歷史小旅行。',hours:'平日與週六有分時段開放',tags:['歷史','古蹟']},
  {id:'kavalan',name:'金車噶瑪蘭威士忌酒廠',cat:'酒廠',emoji:'🥃',address:'宜蘭縣員山鄉員山路二段326號',desc:'參觀威士忌製程、酒堡與園區，是員山最具代表性的觀光工廠之一。',hours:'約 09:00–18:00',tags:['威士忌','觀光工廠']},
  {id:'jimdad',name:"吉姆老爹啤酒工場 Jim & Dad's",cat:'酒廠',emoji:'🍺',address:'宜蘭縣員山鄉員山路二段411號',desc:'精釀啤酒工場、紅磚建築、草地與觀景塔，可與噶瑪蘭酒廠串遊。',hours:'平日約 11:00–18:00；週末 10:00 起；週二常休',tags:['精釀啤酒','觀光工廠']},
  {id:'beihou-temple',name:'北后寺',cat:'文化',emoji:'🏯',address:'宜蘭縣員山鄉八甲路4號',desc:'清幽寺院空間，旁邊就是「聽水」咖啡，可安排成一站。',hours:'白天參訪較合適',tags:['寺院','靜心']}
];

window.YUANSHAN_ROUTES = [
  {icon:'👨‍👩‍👧',name:'親子放電半日',desc:'頭等倉 → 可達羊場 → 勝洋休閒農場',ids:['heads-up','sheep','shengyang']},
  {icon:'🌿',name:'湖光自然線',desc:'望龍埤 → 螃蟹冒泡 → 雙連埤',ids:['wanglongpi','crab-spring','shuanglianpi']},
  {icon:'🍜',name:'員山吃貨線',desc:'魚丸米粉 → Gather 食聚 → 望龍埤鵝肉',ids:['chen-fish','gather','goose']},
  {icon:'🥃',name:'酒廠巡禮',desc:'噶瑪蘭威士忌 → 吉姆老爹精釀 · 品飲請勿駕車',ids:['kavalan','jimdad']}
];
